Update swayswap to fuel-core v0.10 and latest TS SDK with refactoring
FuelLabs/swayswap pull request #383
Opened 2022-09-16 05:17 UTC by luizstacio

This PR updates fuel-core, fuels-ts, fuels-rs to match latest versions. Also includes a refactoring on add liquidity and  contracts

Todo;
- [x] Update fuel-core
- [x] Update contracts
- [x] Update rust tests
- [x] Update scripts
- [x] Update application
- [x] Fix tests
- [x] Refactoring (Goin to be done on a next PR)

2022-09-20 14:10 UTC, QuinnLee submitted a review, later dismissed
lgtm, just a heads up the new version of `react-query` is a pain to upgrade

2022-09-20 17:38 UTC, LuizAsFight commented
As a user I would expect to see `Balance: 0` in DAI coin, even if I don't have balance. Being empty seems buggy.
Specially after changing to swap FROM `DAI`.

https://user-images.githubusercontent.com/8636507/191326309-b075cc92-656f-4a09-bbfa-915062c521f6.mov

2022-09-20 17:58 UTC, luizstacio commented
> 1- As a user I would expect to see `Balance: 0` in DAI coin, even if I don't have balance. Being empty seems buggy. Specially after changing to swap FROM `DAI`.
> 
> 2- When you swap coin sides, "Max" button show/hides, making balance location change. Would be nice to put "Max" button before Balance, then won't move.
> 
>  Screen.Recording.2022-09-20.at.14.39.01.mov

1. This could be nice, but we could create a issue to fix it later, as it is already working on this way
2. I think the max button would look weird before the balance

2022-09-20 18:00 UTC, LuizAsFight commented
Additional to prev comment, we're having too much flicks

See this example of [dieselpools](https://tribaldex.com/dieselpools/)
I know layout is not good but in terms of ux it's very clear and concise, you can keep clicking in anything, things don't move too much

https://user-images.githubusercontent.com/8636507/191329800-4bf53721-3dbc-4c82-80e6-8e810f17067b.mov

now see our swap page
1- there's a lot of more movement
2- if you go slowly through frames, things are changing of place in a different speed. First the Logo goes, then the balance text. balance position changes.

I had fixed this in prev versions but seems like somewhere it started to happen again

Uploading Screen Recording 2022-09-20 at 14.57.27.mov…

2022-09-20 18:13 UTC, luizstacio commented
> Additional to prev comment, we're having too much flicks
> 
> See this example of [dieselpools](https://tribaldex.com/dieselpools/) I know layout is not good but in terms of ux it's very clear and concise, you can keep clicking in anything, things don't move too much
> 
>  Screen.Recording.2022-09-20.at.14.53.15.mov 
> now see our swap page 1- there's a lot of more movement 2- if you go slowly through frames, things are changing of place in a different speed. First the Logo goes, then the balance text. balance position changes.
> 
> I had fixed this in prev versions but seems like somewhere it started to happen again
> 
>  Screen.Recording.2022-09-20.at.14.57.27.mov 
> I won't block the PR because of this layout improvements since it's not bugs. We can work on other issues to improve it

These are valid points can you open an issue for that? I think for this PR going to keep just the scoped things and bugs on functionality

2022-09-20 20:51 UTC, pedronauck requested changes

2022-09-20 20:51 UTC, pedronauck commented on packages/app/src/systems/Pool/hooks/useAddLiquidity.tsx
> +  {} as any
You can remove `any` here and add `as AddLiquidityMachineService`

2022-09-20 21:10 UTC, pedronauck approved these changes

2022-09-20 22:23 UTC, QuinnLee approved these changes

2022-09-20 22:50 UTC, merged

2022-09-21 00:55 UTC, LuizAsFight commented
if we swap a really small value in DAO, resulting in `0.00000000` ETH as output. 
- we get in a infinite loading error

![image](https://user-images.githubusercontent.com/8636507/191390558-f7000e1d-f95b-492f-aa7e-f2517f2d1f32.png)


- this error shows up in console:

```
Error: Script returned non-zero result: 1

{
  "doc": "https://docs.rs/fuel-asm/latest/fuel_asm/enum.PanicReason.html",
  "reason": "unknown"
}

Reverts:
0x0c451a5915bde9057529affc618ea12c917bc2b1e2d65adc24207425053ecfee: 0 {"val":"0x0","pc":"0x14760","is":"0x44d8"}

Receipts:
[
  {
    "type": "Call",
    "from": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "to": "0x0c451a5915bde9057529affc618ea12c917bc2b1e2d65adc24207425053ecfee",
    "amount": "0x2c9",
    "assetId": "0xc4e32fb2bbb59215b639047082596ad073ebc3ccf85d1e84a1738c1d38163e09",
    "gas": "0xcd316",
    "param1": "0x5b98278e",
    "param2": "0x3868",
    "pc": "0x44d8",
    "is": "0x44d8"
  },
  {
    "type": "Revert",
    "id": "0x0c451a5915bde9057529affc618ea12c917bc2b1e2d65adc24207425053ecfee",
    "val": "0x0",
    "pc": "0x14760",
    "is": "0x44d8"
  },
  {
    "type": "ScriptResult",
    "result": "0x1",
    "gasUsed": "0x29d4"
  }
]
    at WP.decodeCallResult (index.bf6744ea.js:409:873)
    at YP.getDecodedValue (index.bf6744ea.js:409:14037)
    at new QP (index.bf6744ea.js:409:13971)
    at new YP (index.bf6744ea.js:409:14281)
    at YP.build (index.bf6744ea.js:409:14456)
    at async die (index.bf6744ea.js:640:11956)
```

2022-09-21 00:58 UTC, LuizAsFight commented
if we start filling a small value in DAI input, then swap ETH to be the input, app suggests a really big number of ETH to change for that small amount of DAI
Also `price impact` goes wrong
Also `1 DAI = X ETH` box goes wrong

maybe underflow problems??


https://user-images.githubusercontent.com/8636507/191390818-de389197-0ecd-4243-b94d-63e3bf7f8ce5.mov

2022-09-21 01:02 UTC, LuizAsFight requested changes

2022-09-21 16:28 UTC, luizstacio commented on .github/workflows/pr.yaml
> +          pnpm recursive install --frozen-lockfile
This was generating a issue, where it didn't correctly install the dependencies. This was happening after updating pnpm action.

2022-09-21 16:32 UTC, luizstacio commented on packages/app/src/systems/Pool/hooks/useAddLiquidity.tsx
> +   * Causing an error in useActor. But it's on development
This follows the same base of useSweap.

2022-09-21 16:37 UTC, luizstacio commented on packages/app/src/systems/Swap/pages/SwapPage.test.tsx
> +  return valBalance;
I think is better to keep like this.

2022-09-21 17:50 UTC, LuizAsFight commented on packages/app/src/systems/Pool/hooks/useAddLiquidity.tsx
> +   * Causing an error in useActor. But it's on development
if you check both `useSwapContext` and `useAddLiquidityContext` usages along the app, no one is using `state`, which makes creating the actor and exporting its state totally useless.

2022-09-21 17:54 UTC, luizstacio commented on packages/app/src/main.tsx
> +// import { inspect } from "@xstate/inspect";
The idea is to have it in an easy way to use in development. if we keep without commenting, it would be embed on the bundle

2022-09-21 18:08 UTC, luizstacio commented on packages/app/src/systems/Pool/components/AddLiquidityButton.tsx
> +      isDisabled={isLoading || notReadyToAddLiquidity}
Is a nice guideline to follow; on the application we already have some negations methods also look on the machine.

2022-09-21 18:13 UTC, luizstacio commented on packages/app/src/systems/Pool/hooks/useAddLiquidity.tsx
> +const isProd = process.env.NODE_ENV === "production";
I add a const `IS_DEVELOPMENT` for now we don't need is production